### ISSUE TITLE
Utility to unwrap a Decoder function

### ISSUE THREAD

**Issue by aeqz** [turboMaCk/aeson-combinators#33]
In cases in which I wanted to implement a `FromJSON` instance by using this package combinators, I missed a utility to unpack the `Decoder` wrapped function:

```haskell
instance FromJSON SomeType where
  parseJSON = fromDecoder $ do
    ... -- Complicated decoding made easier with this package combinators
```

And implemented it myself, or wrote them in this style:

```haskell
instance FromJSON SomeType where
  parseJSON = f
    where
      Decoder f = do
        ... -- Complicated decoding made easier with this package combinators
```

Maybe I missed some already provided way to achieve this? Otherwise, I think that providing such a simple utility would be worth it.

**Comment by turboMaCk** [comment]
Hi @aeqz I think you're 100% right. We should add this function. Are you interested in opening PR for that?

**Comment by aeqz** [comment]
@turboMaCk sure! I will open a PR.
