### ISSUE TITLE
A combinator for missing values

### ISSUE THREAD

**Issue by avanov** [turboMaCk/aeson-combinators#36]
The following version of the `key` allows for running `parseEither` against object mappings with missing optional fields (imagine a "Remember me" checkbox field that may be absent from a payload if not selected by a user). It would be nice to see it distributed within the package:

```haskell
maybeKey :: ACD.Key -> ACD.Decoder a -> ACD.Decoder (Maybe a)
maybeKey t (ACD.Decoder d) = ACD.Decoder $ \case
  AT.Object v -> p >>= maybe (pure Nothing) (fmap Just . d)
    where
        p = v .:? t
  val      -> AT.typeMismatch "Object" val
{-# INLINE maybeKey #-}
```

It's pretty much the same `key` but `.:?` is used instead of `.:` for the inner parser.

**Comment by turboMaCk** [comment]
@avanov do you want to submit PR for this?

**Comment by avanov** [comment]
Thanks!
